export const FETCH_CHURCH_SERVICES = 'FETCH_CHURCH_SERVICES';
export const RECORD_SERVICE_BOOKING = 'RECORD_SERVICE_BOOKING';

// Loading
export const LOADING = 'LOADING';
export const NOT_LOADING = 'NOT_LOADING';